services:
  - type: web
    name: ancore-session-portal
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MEGA_EMAIL
        sync: false
      - key: MEGA_PASSWORD
        sync: false
      - key: PORT
        value: 3000